# constants to configure the look of the frontend

# common
EMAIL:
  ADMIN:
    - admin@brunch-finden.de
  SUPPORT:
    - admin@brunch-finden.de
    - filmkasten@web.de

STAGE: production
DOMAIN:
  #NAME: brunch-finden.me
  NAME: lvh.me:3000
  #FULL_NAME: www.brunch-finden.me
  FULL_NAME: www.lvh.me:3000
  # TOP_LEVEL_DOMAIN_SIZE = 1 for my-domain.de
  # TOP_LEVEL_DOMAIN_SIZE = 2 for my-domain.co.uk or my-domain.com.au
  TOP_LEVEL_DOMAIN_SIZE: 1
SUBDOMAINS:
  SECURE: ''
  BACKEND: ''
  MOBILE: m
BACKEND:
  #DOMAIN: www.brunch-finden.me
  DOMAIN: www.lvh.me:3000
  PATH: /backend
  