# List of bad word. They are forbitten to use with user names or emails.
---
- hitler
- nazi
- faschist
- fascho
- nazionalsozialist
- npd
- nsdap
- porno
- pornograf
- schwul
- schwuchtel
- penis
- pimmel
- fotze
- votze
- vagina
- ficken
- bumsen
- admin
