# constants to configure the look of the frontend

# common
EMAIL:
  ADMIN:
    - admin@brunch-finden.de
  SUPPORT:
    - admin@brunch-finden.de
    - filmkasten@web.de

STAGE: production
DOMAIN:
  NAME: 'brunch-finden.de'
  #NAME: '83.169.4.42'
  FULL_NAME: 'www.brunch-finden.de'
  #FULL_NAME: '83.169.4.42'
  # TOP_LEVEL_DOMAIN_SIZE = 1 for my-domain.de
  # TOP_LEVEL_DOMAIN_SIZE = 2 for my-domain.co.uk or my-domain.com.au
  TOP_LEVEL_DOMAIN_SIZE: 1
SUBDOMAINS:
  SECURE: ''
  BACKEND: ''
  MOBILE: m
BACKEND:
  DOMAIN: 'www.brunch-finden.de'
  #DOMAIN: '83.169.4.42'
  PATH: '/backend'
  