- 0815.ru
- 10minutemail.com
- 3d-painting.com
- antichef.net
- BeefMilk.com
- binkmail.com
- bio-muesli.info
- bio-muesli.net
- bobmail.info
- cust.in
- despammed.com
- dingbone.com
- discardmail.com
- discardmail.de
- dontsendmespam.de
- emailias.com
- ero-tube.org
- film-blog.biz
- fr33mail.info
- fudgerub.com
- geschent.biz
- great-host.in
- guerillamail.com
- hulapla.de
- imails.info
- jetable.org
- jnxjn.com
- kulturbetrieb.info
- kurzepost.de
- lookugly.com
- m4ilweb.info
- mail4trash.com
- mailexpire.com
- mailinator.com
- mailinator.net
- mailnull.com
- misterpinball.de
- mypartyclip.de
- nervmich.net
- nervtmich.net
- nomail2me.com
- nurfuerspam.de
- objectmail.com
- owlpic.com
- politikerclub.de
- proxymail.eu
- rcpt.at
- recode.me
- s0ny.net
- safetymail.info
- safetypost.de
- sandelf.de
- smellfear.com
- sneakemail.com
- snkmail.com
- sofort-mail.de
- spam.la
- spambog.com
- spambog.de
- spambog.ru
- spamex.com
- spamgourmet.com
- spamherelots.com
- spammotel.com
- spamtrail.com
- super-auswahl.de
- suremail.info
- teewars.org
- tempalias.com
- tempemail.net
- temporaryinbox.com
- thanksnospam.info
- thisisnotmyrealemail.com
- trash2009.com
- trashemail.de
- trash-mail.at
- trash-mail.com
- trash2009.com
- trashmail.at
- trashmail.me
- trashmail.net
- trashmail.ws
- watch-harry-potter.com
- watchfull.net
- webm4il.info
- wegwerf-email.net
- wegwerfadresse.de
- wegwerfemail.de
- wegwerfmail.de
- wegwerfmail.net
- wegwerfmail.org
- willhackforfood.biz
- yopmail.com
- zippymail.info 
- 799fu.com
- mailondandan.com
- mailabconline.com
- lvfityou.com
- lvheremeetyou.com
- fallloveinlv.com
- nokiamail.com
- lvheremttyou.com
- highheelcl.com
- need-mail.com
- buygolfmall.com
- showcoachfactory.com
- lvtimeshow.com
- lvhotstyle.com
